-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "LearnSkill"
local A_2 = 
{
    ["Skill"] = "Agility I", 
    ["SkillTreeType"] = "Character"
}
local Event = game:GetService("Workspace").Living.ghgtgvtv.RemoteFunction
Event:InvokeServer(A_1, A_2) 

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "LearnSkill"
local A_2 = 
{
    ["Skill"] = "Agility II", 
    ["SkillTreeType"] = "Character"
}
local Event = game:GetService("Workspace").Living.ghgtgvtv.RemoteFunction
Event:InvokeServer(A_1, A_2)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "LearnSkill"
local A_2 = 
{
    ["Skill"] = "Agility III", 
    ["SkillTreeType"] = "Character"
}
local Event = game:GetService("Workspace").Living.ghgtgvtv.RemoteFunction
Event:InvokeServer(A_1, A_2)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "LearnSkill"
local A_2 = 
{
    ["Skill"] = "Worthiness I", 
    ["SkillTreeType"] = "Character"
}
local Event = game:GetService("Workspace").Living.ghgtgvtv.RemoteFunction
Event:InvokeServer(A_1, A_2)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "LearnSkill"
local A_2 = 
{
    ["Skill"] = "Worthiness II", 
    ["SkillTreeType"] = "Character"
}
local Event = game:GetService("Workspace").Living.ghgtgvtv.RemoteFunction
Event:InvokeServer(A_1, A_2)
